version: '3.9'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env-non-dev
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  delivery:
    build:
      context: .
    container_name: delivery
    ports:
      - '8001:8000'
    depends_on:
      - postgres-db
    env_file:
      - .env-non-dev
    restart: on-failure:5
    healthcheck:
      test: curl -f http://localhost:8000 || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  pg_data:


